### ISSUE TITLE
Tournaments should have a row at the top for KOM times

### ISSUE THREAD

**Issue by BBischof** [adam-conway/stavaelo#23]
One row in the table should be the KOM times for all the segments as an easy visual understanding of how long these segments are. Similarly, it'd be nice to show: 
```
Distance
Ascent
```
for the segments somewhere.

**Comment by adam-conway** [comment]
Yeah I like this and shouldn't be too hard to implement. The distance for a segment is already stored in the DB but isn't being displayed. The total elevation gained for a particular segment is being displayed on [this page](https://evening-garden-22044.herokuapp.com/segments) but for some reason that I haven't looked into yet, not every segment is returning the correct data for that.

**Comment by adam-conway** [comment]
Can we either consider this closed @BBischof or update the name? We have best overall times now but don't have both the distance and ascent showing yet.

**Comment by BBischof** [comment]
Those can be handled separately and close this.
